name: Pylint

# job 1: get python files changed
# job 2: run pylint on those files with a required minimum score of 7
# needs requirements.txt with dependencies imported in the files tested

on:
  pull_request:
    branches:
      - main

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      py: ${{ steps.changes.outputs.py }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changes
        run: |
          echo "py=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .py$ | xargs)" >> $GITHUB_OUTPUT
  pylint:
    runs-on: ubuntu-latest
    needs: changedfiles
    strategy:
      matrix:
        python-version: ["3.8"]
    if: ${{needs.changedfiles.outputs.py}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
          pylint ${{needs.changedfiles.outputs.py}} --fail-under=7
